# Tensorflow2.0 小练习

In [1]:
import tensorflow as tf # 机器学习与深度学习的框架，提供tensor操作，支持GPU加速
import numpy as np # 数值计算库，处理矩阵运算

## 实现softmax函数

In [2]:
# SOFTMAX 即对x元素求e^x，再返回prob_x = e^x/sum(e^x)
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    
    # keepdims=True是保持维度，防止降维，使用np.max防e^x溢出
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))   
    sum_exp_x = np.sum(exp_x, axis=-1, keepdims=True)
    prob_x = exp_x / sum_exp_x

    # 需要转为tensor匹配输出
    prob_x = tf.convert_to_tensor(prob_x)

    return prob_x

test_data = np.random.normal(size=[10, 5])

# 为什么这里test_data不用axis=-1就能与tf.nn.softmax(test_data, axis=-1)进行运算?
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [3]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    sig_x = 1 / (1 + np.exp(-x))
    
    # clip_by_value的作用是将超出范围的值截断为边界值
    # prob_x = tf.clip_by_value(sig_x, 0.00000001, 0.99999999) # 防止溢出， 避免概率为0或1
    
    # 转换为tensor
    prob_x = tf.convert_to_tensor(sig_x)
    
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [4]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########

    # softmax返回最后一维的概率，这里也是对最后一维求损失
    loss = -np.sum(label * np.log(x + 1e-15), axis=-1)

    # 对每个样本损失取平均
    loss = np.mean(loss)

    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [6]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########

    # 忽视了label = 0的情况
    # loss = np.sum(label * np.log(x+1e-15),axis= -1)
    
    # 二分类
    loss = label*np.log(x +1e-7)+(1-label)*np.log(1-x+1e-7)
    loss= -np.mean(loss)
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 1. 1. 1. 1. 1. 1. 0. 0. 1.]


True